apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: providers.frontman.io
spec:
  group: frontman.io
  names:
    kind: Provider
    listKind: ProviderList
    plural: providers
    singular: provider
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - description: ""
      jsonPath: .spec.interval
      name: Refresh
      type: string
    - description: ""
      jsonPath: .status.numberOfReleases
      name: Releases
      type: string
    name: v1
    schema:
      openAPIV3Schema:
        properties:
          status:
            nullable: false
            properties:
              numberOfReleases:
                nullable: false
                type: integer
              versions:
                items:
                  nullable: false
                  type: string
                nullable: true
                type: array
            required:
            - numberOfReleases
            type: object
          spec:
            nullable: false
            properties:
              type:
                enum:
                - File
                - AzureBlob
                type: string
              file:
                nullable: false
                properties:
                  path:
                    nullable: true
                    type: string
                type: object
              azureBlob:
                nullable: false
                properties:
                  connectionString:
                    nullable: true
                    type: string
                  containerName:
                    nullable: true
                    type: string
                  root:
                    nullable: true
                    type: string
                type: object
              interval:
                default: 5m
                nullable: true
                pattern: (\d+(?:\.\d+)?)(ms|s|m|h)
                type: string
            required:
            - type
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: releases.frontman.io
spec:
  group: frontman.io
  names:
    kind: Release
    listKind: ReleaseList
    plural: releases
    singular: release
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - description: ""
      jsonPath: .spec.url
      name: Url
      type: string
    - description: ""
      jsonPath: .spec.version
      name: Version
      type: string
    - description: ""
      jsonPath: .status.previousVersion
      name: Previous
      type: string
    - description: ""
      jsonPath: .status.message
      name: Message
      type: string
    name: v1
    schema:
      openAPIV3Schema:
        properties:
          status:
            nullable: false
            properties:
              currentVersion:
                nullable: true
                type: string
              previousVersion:
                nullable: true
                type: string
              message:
                nullable: true
                type: string
            type: object
          spec:
            nullable: false
            properties:
              provider:
                nullable: true
                type: string
              url:
                nullable: true
                type: string
              version:
                nullable: true
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: k8s-frontman-role
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - pods/log
  - services
  - endpoints
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
  - update
  - get
- apiGroups:
  - frontman.io
  resources:
  - providers
  - releases
  verbs:
  - '*'
- apiGroups:
  - frontman.io
  resources:
  - providers/status
  - releases/status
  verbs:
  - get
  - update
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: k8s-frontman-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: k8s-frontman-role
subjects:
- kind: ServiceAccount
  name: default
  namespace: k8s-frontman-system
---
apiVersion: v1
kind: Namespace
metadata:
  name: k8s-frontman-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    operator: k8s-frontman
  name: k8s-frontman
  namespace: k8s-frontman-system
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      operator: k8s-frontman
  template:
    metadata:
      labels:
        operator: k8s-frontman
    spec:
      containers:
      - env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: ghcr.io/pmdevers/k8s-frontman:1.2.3-alpha0001
        name: k8s-frontman
        ports:
        - containerPort: 8080
          name: http
        resources:
          limits:
            cpu: 100m
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 512Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          runAsGroup: 2024
          runAsNonRoot: true
          runAsUser: 2024
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      serviceAccountName: default
---
apiVersion: v1
kind: Service
metadata:
  labels:
    operator: k8s-frontman
  name: k8s-frontman
  namespace: k8s-frontman-system
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    operator: k8s-frontman
---

